local M = {}

local palettes = {
  dark = {
    bg = "#1b1d1e",
    bg_alt = "#232627",
    bg_float = "#26292a",
    bg_visual = "#4d4f4c",
    bg_cursorline = "#2b2e2f",
    bg_search = "#5c5a24",
    fg = "#c5c5be",
    fg_alt = "#dadad5",
    fg_muted = "#909495",
    fg_subtle = "#6e6e6e",
    fg_pick = "#d7d7d2",
    fg_hidden = "#9da1a2",
    fg_ignored = "#a8acab",
    comment = "#737271",
    border = "#505354",
    accent = "#f3fd21",
    accent_soft = "#feed6c",
    yellow = "#e6db43",
    green = "#c8be46",
    blue = "#909495",
    cyan = "#a2a2a5",
    magenta = "#9a999d",
    red = "#fff27c",
    orange = "#fff68d",
    error = "#fff27c",
    warn = "#feed6c",
    info = "#909495",
    hint = "#a2a2a5",
    ok = "#c8be46",
    diff_add = "#31361f",
    diff_change = "#353528",
    diff_delete = "#423530",
    diff_text = "#4d4f4c",
  },
  light = {
    bg = "#e8e6dd",
    bg_alt = "#ddd9cd",
    bg_float = "#f0ede4",
    bg_visual = "#d3cfbe",
    bg_cursorline = "#d9d4c5",
    bg_search = "#f2e98c",
    fg = "#2d3031",
    fg_alt = "#151718",
    fg_muted = "#4f5354",
    fg_subtle = "#666a6b",
    fg_pick = "#3a3d3e",
    fg_hidden = "#6a6e6f",
    fg_ignored = "#5e6364",
    comment = "#737074",
    border = "#8d908d",
    accent = "#8f8400",
    accent_soft = "#a99a12",
    yellow = "#867900",
    green = "#6d6a1d",
    blue = "#5a6064",
    cyan = "#666a6d",
    magenta = "#6d6b72",
    red = "#8c6f16",
    orange = "#9b7814",
    error = "#9c5a20",
    warn = "#8f7c00",
    info = "#4f5d6b",
    hint = "#5f6669",
    ok = "#667220",
    diff_add = "#d7e2c3",
    diff_change = "#e6dfbb",
    diff_delete = "#ead2c5",
    diff_text = "#d8cf9d",
  },
}

local function set_hl(groups)
  for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

local function base_groups(c)
  return {
    ColorColumn = { bg = c.bg_alt },
    Conceal = { fg = c.fg_muted },
    CurSearch = { fg = c.bg, bg = c.accent, bold = true },
    Cursor = { fg = c.bg, bg = c.accent },
    CursorColumn = { bg = c.bg_cursorline },
    CursorIM = { fg = c.bg, bg = c.accent },
    CursorLine = { bg = c.bg_cursorline },
    CursorLineNr = { fg = c.accent, bg = c.bg_cursorline, bold = true },
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.ok },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { bg = c.diff_text, bold = true },
    Directory = { fg = c.accent, bold = true },
    EndOfBuffer = { fg = c.bg_alt },
    ErrorMsg = { fg = c.error, bold = true },
    FloatBorder = { fg = c.border, bg = c.bg_float },
    FloatTitle = { fg = c.accent, bg = c.bg_float, bold = true },
    FoldColumn = { fg = c.fg_subtle, bg = c.bg },
    Folded = { fg = c.fg_muted, bg = c.bg_alt },
    IncSearch = { fg = c.bg, bg = c.accent_soft, bold = true },
    LineNr = { fg = c.fg_subtle },
    MatchParen = { fg = c.accent, bold = true, underline = true },
    ModeMsg = { fg = c.fg_alt, bold = true },
    MoreMsg = { fg = c.ok, bold = true },
    NonText = { fg = c.border },
    Normal = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_float },
    NormalNC = { fg = c.fg, bg = c.bg },
    Pmenu = { fg = c.fg, bg = c.bg_float },
    PmenuSbar = { bg = c.bg_alt },
    PmenuSel = { fg = c.bg, bg = c.accent, bold = true },
    PmenuThumb = { bg = c.border },
    Search = { fg = c.bg, bg = c.yellow },
    SignColumn = { bg = c.bg },
    SpecialKey = { fg = c.fg_subtle },
    SpellBad = { undercurl = true, sp = c.error },
    SpellCap = { undercurl = true, sp = c.warn },
    SpellLocal = { undercurl = true, sp = c.info },
    SpellRare = { undercurl = true, sp = c.hint },
    StatusLine = { fg = c.fg, bg = c.bg_alt },
    StatusLineNC = { fg = c.fg_subtle, bg = c.bg_alt },
    TabLine = { fg = c.fg_muted, bg = c.bg_alt },
    TabLineFill = { bg = c.bg_alt },
    TabLineSel = { fg = c.bg, bg = c.accent, bold = true },
    Title = { fg = c.accent, bold = true },
    VertSplit = { fg = c.border },
    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.bg_visual },
    WarningMsg = { fg = c.warn, bold = true },
    WinBar = { fg = c.fg_muted, bg = c.bg },
    WinBarNC = { fg = c.fg_subtle, bg = c.bg },
    WinSeparator = { fg = c.border },
    Boolean = { fg = c.orange, bold = true },
    Character = { fg = c.green },
    Comment = { fg = c.comment, italic = true },
    Conditional = { fg = c.accent_soft, bold = true },
    Constant = { fg = c.orange },
    Define = { fg = c.accent_soft },
    Delimiter = { fg = c.fg_muted },
    Function = { fg = c.accent },
    Identifier = { fg = c.fg_alt },
    Include = { fg = c.accent_soft },
    Keyword = { fg = c.yellow, bold = true },
    Label = { fg = c.accent_soft },
    Number = { fg = c.orange },
    Operator = { fg = c.fg_alt },
    PreProc = { fg = c.accent_soft },
    Special = { fg = c.accent_soft },
    Statement = { fg = c.yellow, bold = true },
    StorageClass = { fg = c.yellow },
    String = { fg = c.green },
    Tag = { fg = c.accent },
    Todo = { fg = c.bg, bg = c.accent_soft, bold = true },
    Type = { fg = c.cyan, italic = true },
    Typedef = { fg = c.cyan, bold = true },
    ["@comment"] = { link = "Comment" },
    ["@constant"] = { link = "Constant" },
    ["@constructor"] = { fg = c.accent_soft },
    ["@function"] = { link = "Function" },
    ["@keyword"] = { link = "Keyword" },
    ["@number"] = { link = "Number" },
    ["@operator"] = { link = "Operator" },
    ["@parameter"] = { fg = c.fg_alt },
    ["@property"] = { fg = c.fg_alt },
    ["@punctuation.delimiter"] = { fg = c.fg_muted },
    ["@punctuation.bracket"] = { fg = c.fg_muted },
    ["@string"] = { link = "String" },
    ["@tag"] = { link = "Tag" },
    ["@type"] = { link = "Type" },
    ["@variable"] = { fg = c.fg },
  }
end

local function plugin_groups(c)
  return {
    GitSignsAdd = { fg = c.ok },
    GitSignsChange = { fg = c.warn },
    GitSignsDelete = { fg = c.error },
    LazyButton = { fg = c.fg, bg = c.bg_alt },
    LazyButtonActive = { fg = c.bg, bg = c.accent, bold = true },
    LazyComment = { fg = c.fg_subtle },
    LazyCommit = { fg = c.accent_soft },
    LazyCommitIssue = { fg = c.orange, underline = true },
    LazyCommitScope = { fg = c.cyan },
    LazyCommitType = { fg = c.yellow, bold = true },
    LazyDimmed = { fg = c.fg_subtle },
    LazyDir = { fg = c.cyan },
    LazyError = { fg = c.error, bold = true },
    LazyH1 = { fg = c.accent, bold = true },
    LazyH2 = { fg = c.yellow, bold = true },
    LazyInfo = { fg = c.info },
    LazyLocal = { fg = c.green },
    LazyNoCond = { fg = c.fg_subtle },
    LazyNormal = { fg = c.fg, bg = c.bg_float },
    LazyProgressDone = { fg = c.accent },
    LazyProgressTodo = { fg = c.border },
    LazyProp = { fg = c.cyan },
    LazyReasonCmd = { fg = c.yellow },
    LazyReasonEvent = { fg = c.cyan },
    LazyReasonFt = { fg = c.green },
    LazyReasonImport = { fg = c.magenta },
    LazyReasonKeys = { fg = c.orange },
    LazyReasonPlugin = { fg = c.accent_soft },
    LazyReasonRuntime = { fg = c.info },
    LazyReasonSource = { fg = c.fg_muted },
    LazyReasonStart = { fg = c.accent },
    LazySpecial = { fg = c.accent, bold = true },
    LazyTaskOutput = { fg = c.fg_muted },
    LazyUrl = { fg = c.info, underline = true },
    LazyValue = { fg = c.fg_alt },
    LazyWarning = { fg = c.warn, bold = true },
    NoiceCmdline = { fg = c.fg, bg = c.bg_float },
    NoiceCmdlineIcon = { fg = c.accent, bg = c.bg_float },
    NoiceCmdlinePopup = { fg = c.fg, bg = c.bg_float },
    NoiceCmdlinePopupBorder = { fg = c.border, bg = c.bg_float },
    NoiceCmdlinePopupBorderSearch = { fg = c.accent_soft, bg = c.bg_float },
    NoiceCmdlinePopupTitle = { fg = c.accent, bg = c.bg_float, bold = true },
    NoiceConfirmBorder = { fg = c.accent, bg = c.bg_float },
    NoiceMini = { fg = c.fg_muted, bg = c.bg_alt },
    NoicePopupBorder = { fg = c.border, bg = c.bg_float },
    NoicePopupmenuBorder = { fg = c.border, bg = c.bg_float },
    NotifyBackground = { bg = c.bg_float },
    NotifyERRORBorder = { fg = c.error, bg = c.bg_float },
    NotifyWARNBorder = { fg = c.warn, bg = c.bg_float },
    NotifyINFOBorder = { fg = c.info, bg = c.bg_float },
    NotifyDEBUGBorder = { fg = c.border, bg = c.bg_float },
    NotifyTRACEBorder = { fg = c.magenta, bg = c.bg_float },
    NotifyERRORTitle = { fg = c.error, bold = true },
    NotifyWARNTitle = { fg = c.warn, bold = true },
    NotifyINFOTitle = { fg = c.info, bold = true },
    NotifyDEBUGTitle = { fg = c.fg_muted, bold = true },
    NotifyTRACETitle = { fg = c.magenta, bold = true },
    SnacksDashboardDesc = { fg = c.fg_muted },
    SnacksDashboardDir = { fg = c.fg_subtle },
    SnacksDashboardFile = { fg = c.fg_alt },
    SnacksDashboardFooter = { fg = c.fg_muted },
    SnacksDashboardHeader = { fg = c.accent, bold = true },
    SnacksDashboardIcon = { fg = c.accent_soft },
    SnacksDashboardKey = { fg = c.yellow, bold = true },
    SnacksDashboardNormal = { fg = c.fg, bg = c.bg },
    SnacksDashboardSpecial = { fg = c.accent },
    SnacksFooter = { fg = c.fg_muted, bg = c.bg_float },
    SnacksFooterDesc = { fg = c.fg, bg = c.bg_float },
    SnacksFooterKey = { fg = c.accent, bg = c.bg_float, bold = true },
    SnacksInputBorder = { fg = c.border, bg = c.bg_float },
    SnacksInputNormal = { fg = c.fg, bg = c.bg_float },
    SnacksInputTitle = { fg = c.accent, bg = c.bg_float, bold = true },
    SnacksNormal = { fg = c.fg, bg = c.bg_float },
    SnacksNormalNC = { fg = c.fg_muted, bg = c.bg_float },
    SnacksNotifierHistory = { fg = c.fg, bg = c.bg },
    SnacksPicker = { fg = c.fg, bg = c.bg_float },
    SnacksPickerBold = { fg = c.fg_alt, bold = true },
    SnacksPickerCode = { fg = c.green },
    SnacksPickerComment = { fg = c.comment, italic = true },
    SnacksPickerDelim = { fg = c.border },
    SnacksPickerDimmed = { fg = c.fg_subtle },
    SnacksPickerDir = { fg = c.fg_muted },
    SnacksPickerDirectory = { fg = c.fg_pick, bold = true },
    SnacksPickerFile = { fg = c.fg_pick },
    SnacksPickerGitAuthor = { fg = c.fg_muted },
    SnacksPickerGitBranch = { fg = c.yellow },
    SnacksPickerGitBranchCurrent = { fg = c.accent, bold = true },
    SnacksPickerGitBreaking = { fg = c.error, bold = true },
    SnacksPickerGitCommit = { fg = c.accent_soft },
    SnacksPickerGitDate = { fg = c.fg_subtle },
    SnacksPickerGitDetached = { fg = c.orange },
    SnacksPickerGitIssue = { fg = c.orange, underline = true },
    SnacksPickerGitMsg = { fg = c.fg },
    SnacksPickerGitScope = { fg = c.cyan },
    SnacksPickerGitStatus = { fg = c.fg_muted },
    SnacksPickerGitStatusAdded = { fg = c.ok },
    SnacksPickerGitStatusCopied = { fg = c.cyan },
    SnacksPickerGitStatusDeleted = { fg = c.error },
    SnacksPickerGitStatusModified = { fg = c.warn },
    SnacksPickerGitStatusRenamed = { fg = c.accent_soft },
    SnacksPickerGitStatusStaged = { fg = c.accent, bold = true },
    SnacksPickerGitStatusUnmerged = { fg = c.orange, bold = true },
    SnacksPickerGitStatusUntracked = { fg = c.fg_hidden },
    SnacksPickerGitType = { fg = c.yellow, bold = true },
    SnacksPickerIdx = { fg = c.fg_subtle },
    SnacksPickerItalic = { fg = c.fg, italic = true },
    SnacksPickerLabel = { fg = c.accent_soft },
    SnacksPickerLink = { fg = c.info, underline = true },
    SnacksPickerLinkBroken = { fg = c.error, strikethrough = true },
    SnacksPickerMatch = { fg = c.accent, bold = true },
    SnacksPickerPathHidden = { fg = c.fg_hidden },
    SnacksPickerPathIgnored = { fg = c.fg_ignored, italic = true },
    SnacksPickerPickWin = { fg = c.fg_muted, bg = c.bg_alt },
    SnacksPickerPickWinCurrent = { fg = c.bg, bg = c.accent, bold = true },
    SnacksPickerRow = { fg = c.accent_soft },
    SnacksPickerCol = { fg = c.yellow },
    SnacksPickerRule = { fg = c.border },
    SnacksPickerSpinner = { fg = c.accent },
    SnacksStatusColumnMark = { fg = c.accent, bold = true },
    SnacksTitle = { fg = c.accent, bg = c.bg_float, bold = true },
    SnacksWinBar = { fg = c.fg_muted, bg = c.bg_float },
    SnacksWinBarNC = { fg = c.fg_subtle, bg = c.bg_float },
    SnacksWinKey = { fg = c.accent, bold = true },
    SnacksWinKeyDesc = { fg = c.fg },
    SnacksWinKeySep = { fg = c.border },
    SnacksWinSeparator = { fg = c.border },
    WhichKey = { fg = c.accent, bold = true },
    WhichKeyBorder = { fg = c.border, bg = c.bg_float },
    WhichKeyDesc = { fg = c.fg },
    WhichKeyGroup = { fg = c.yellow, bold = true },
    WhichKeyIcon = { fg = c.accent_soft },
    WhichKeyNormal = { fg = c.fg, bg = c.bg_float },
    WhichKeySeparator = { fg = c.fg_subtle },
    WhichKeyTitle = { fg = c.accent, bg = c.bg_float, bold = true },
    WhichKeyValue = { fg = c.fg_muted },
    WhichKeyColorYellow = { fg = c.accent },
    WhichKeyColorOrange = { fg = c.orange },
    WhichKeyColorGreen = { fg = c.ok },
    WhichKeyColorBlue = { fg = c.info },
    WhichKeyColorCyan = { fg = c.cyan },
    WhichKeyColorPurple = { fg = c.magenta },
    WhichKeyColorRed = { fg = c.error },
    WhichKeyColorGrey = { fg = c.fg_subtle },
    WhichKeyColorAzure = { fg = c.info },
  }
end

function M.load(variant)
  local c = palettes[variant] or palettes.dark

  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.o.termguicolors = true
  vim.g.colors_name = variant == "light" and "batman-light" or "batman"
  vim.o.background = variant == "light" and "light" or "dark"

  vim.g.terminal_color_0 = c.bg
  vim.g.terminal_color_1 = c.yellow
  vim.g.terminal_color_2 = c.green
  vim.g.terminal_color_3 = c.accent
  vim.g.terminal_color_4 = c.blue
  vim.g.terminal_color_5 = c.magenta
  vim.g.terminal_color_6 = c.cyan
  vim.g.terminal_color_7 = c.fg
  vim.g.terminal_color_8 = c.border
  vim.g.terminal_color_9 = c.orange
  vim.g.terminal_color_10 = c.green
  vim.g.terminal_color_11 = c.accent_soft
  vim.g.terminal_color_12 = c.info
  vim.g.terminal_color_13 = c.magenta
  vim.g.terminal_color_14 = c.hint
  vim.g.terminal_color_15 = c.fg_alt

  set_hl(base_groups(c))
  set_hl(plugin_groups(c))
end

return M
