plugins=(git)

ZSH_THEME="spaceship"

SPACESHIP_PROMPT_ORDER=(
  dir
  git
  exec_time
  exit_code
  line_sep
  char
)

SPACESHIP_CHAR_SYMBOL="λ"
SPACESHIP_CHAR_SUFFIX=" "
DISABLE_AUTO_TITLE=true
SPACESHIP_TITLE_SHOW=false
SPACESHIP_PROMPT_ASYNC=true
SPACESHIP_PROMPT_ADD_NEWLINE=false
